---
- name: Workstation customization playbook
  hosts: localhost
  connection: local
  become: false

  vars:
    applications:
      - disk-inventory-x
      - firefox 
      - iterm2
      - mactracker
      - rectangle
      - visual-studio-code
      - homebrew/cask-fonts/font-sauce-code-pro-nerd-font
      - font-source-code-pro
      - github
      - postman
      - keepassxc
      - macfuse
      - veracrypt
      - powershell
      - plex
      - suspicious-package
      - cyberduck
      - handbrake
      - iina
    
    install_oh_my_zsh:  true

    brew_taps:
      - homebrew/autoupdate
    
  tasks:
    - name: Check for installed apps(casks)
      shell: brew list --cask | grep {{ item }}
      register: installed_applications
      with_items: "{{ applications }}"
      ignore_errors: true

    - name: Install required Homebrew Taps
      shell: brew tap {{ item }}
      with_items: "{{ brew_taps }}"

    - name: Install Apps with brew cask
      shell: brew install --cask {{ item }}
      with_items: "{{ applications }}"
      when: 'item not in installed_applications.results|map(attribute="stdout")'

    - name: Set Brew autoupdate
      shell: brew autoupdate start --enable-notification --upgrade
      ignore_errors: true

    - name: Install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: install_oh_my_zsh == true
      tags: install_oh_my_zsh
      ignore_errors: true
    
    - name: Replace the Oh My Zsh theme
      ansible.builtin.replace:
        path: ~/.zshrc
        regexp: '\brobbyrussell'
        replace: 'amuse'
      when: install_oh_my_zsh == true
